// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDn8C8H8rK1MNxm-Alraj0eT5-v8bGOMA',
    appId: '1:792085183958:web:a55ba5655c0f1927b1f877',
    messagingSenderId: '792085183958',
    projectId: 'task-app-ab2cf',
    authDomain: 'task-app-ab2cf.firebaseapp.com',
    storageBucket: 'task-app-ab2cf.firebasestorage.app',
    measurementId: 'G-E64P88CCVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZihwvbzuYVigoxp5c1Rmr5lS92gEzno',
    appId: '1:792085183958:android:1acedae82dacdc81b1f877',
    messagingSenderId: '792085183958',
    projectId: 'task-app-ab2cf',
    storageBucket: 'task-app-ab2cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrOP0MtDS5vuA15P1YI9a5qnhD-w-LyUE',
    appId: '1:792085183958:ios:e030cd5dd6cb5a60b1f877',
    messagingSenderId: '792085183958',
    projectId: 'task-app-ab2cf',
    storageBucket: 'task-app-ab2cf.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrOP0MtDS5vuA15P1YI9a5qnhD-w-LyUE',
    appId: '1:792085183958:ios:e030cd5dd6cb5a60b1f877',
    messagingSenderId: '792085183958',
    projectId: 'task-app-ab2cf',
    storageBucket: 'task-app-ab2cf.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDn8C8H8rK1MNxm-Alraj0eT5-v8bGOMA',
    appId: '1:792085183958:web:fd12b6ebb0e10086b1f877',
    messagingSenderId: '792085183958',
    projectId: 'task-app-ab2cf',
    authDomain: 'task-app-ab2cf.firebaseapp.com',
    storageBucket: 'task-app-ab2cf.firebasestorage.app',
    measurementId: 'G-37FN7TCJJZ',
  );
}
